import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Alle onderwerpen blijven automatisch zichtbaar, ook nieuw cursusmateriaal.
// Leesbare namen en volgorde worden ingesteld in sidebars-labels.ts.
const sidebars: SidebarsConfig = {
  allTopicsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
