import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// The source course always exposes every topic, including newly added material.
const sidebars: SidebarsConfig = {
  allTopicsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
