const { test } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { assembleCourse, loadConfig } = require('../assemble-course.cjs');
const { buildExercises } = require('../build-exercises.cjs');

async function put(root, file, content) {
  await fs.mkdir(path.dirname(path.join(root, file)), { recursive: true });
  await fs.writeFile(path.join(root, file), content);
}

async function fixture(t) {
  const root = await fs.mkdtemp(path.join(os.tmpdir(), 'course-test-'));
  t.after(() => fs.rm(root, { recursive: true, force: true }));
  const sourceDir = path.join(root, 'source');
  const courseDir = path.join(root, 'course');
  for (const [file, content] of Object.entries({
    'docs/index.md': '# Course',
    'docs/01-topic/01-first.md': '---\nid: introduction\n---\n# First',
    'docs/01-topic/02-second.mdx': '# Second',
    'docs/01-topic/_category_.json': '{"label":"Topic"}',
    'docs/01-topic/image.png': 'image',
    'docs/_partials/example.mdx': 'An imported fragment',
    'docs/other/hidden.md': '# Hidden',
    'docs/exercises/README.md': '# Exercise catalog',
    'docs/exercises/topic/one/README.md': '# Exercise one',
    'docs/exercises/topic/one/solution/index.ts': 'console.log(1)',
    'docs/exercises/topic/one/solution/README.md': 'Download instructions, not a lesson',
    'docs/exercises/topic/two/README.md': '# Exercise two',
    'docs/exercises/topic/two/starter/index.ts': 'console.log(2)',
    'src/components/Test.tsx': 'export default () => null;',
    'static/quizzes/test.json': '{}',
    'static/exercises/obsolete/solution.zip': 'stale archive',
  })) await put(sourceDir, file, content);
  await put(courseDir, 'docusaurus.config.ts', `
    import {themes} from 'prism-react-renderer';
    import type {Config} from '@docusaurus/types';
    export default async (): Promise<Config> => ({
      title: 'Fixture', url: 'https://example.com', baseUrl: '/',
      customFields: {course: {extraDocs: ['other/hidden']}},
      presets: [['classic', {docs: {sidebarPath: './sidebars.ts'}, blog: false}]],
      themeConfig: {prism: {theme: themes.github}},
    });
  `);
  await put(courseDir, 'sidebars.ts', `export default {
    theory: ['index', {Topic: [
      {type: 'category', label: 'Topic', link: {type: 'doc', id: 'topic/introduction'},
       items: [{type: 'ref', id: 'topic/second'}, {type: 'link', label: 'Web', href: 'https://example.com'}]},
    ]}],
    exercises: ['exercises/topic/one/README'],
  };`);
  return { root, sourceDir, courseDir };
}

test('assembles TS config, nested sidebar shorthand, category links, refs, front matter IDs and exercise downloads', async (t) => {
  const options = await fixture(t);
  const result = await assembleCourse(options);
  assert.deepEqual(result.documents, [
    '01-topic/01-first.md', '01-topic/02-second.mdx', 'exercises/topic/one/README.md', 'index.md', 'other/hidden.md',
  ]);
  await fs.access(path.join(result.outputDir, 'docs/01-topic/image.png'));
  await fs.access(path.join(result.outputDir, 'docs/_partials/example.mdx'));
  await assert.rejects(fs.access(path.join(result.outputDir, 'docs/exercises/topic/two')));
  await assert.rejects(fs.access(path.join(result.outputDir, 'static/exercises/obsolete')));
  await buildExercises(result.outputDir);
  const zip = path.join(result.outputDir, 'static/exercises/topic/one/solution.zip');
  const contents = execFileSync('unzip', ['-Z1', zip], { encoding: 'utf8' });
  assert.match(contents, /index\.ts/);
  assert.match(contents, /README\.md/);
  const generated = await loadConfig(path.join(result.outputDir, 'docusaurus.config.cjs'));
  assert.equal(generated.title, 'Fixture');
  assert.deepEqual(generated.presets[0][1].docs.include, result.documents);
  assert.ok(generated.themeConfig.prism.theme);
  // Assembly never writes lesson material into the configuration repository root.
  assert.deepEqual((await fs.readdir(options.courseDir)).sort(), ['.course', 'docusaurus.config.ts', 'sidebars.ts']);
});

test('autogenerated folders select all their pages, and reassembly removes old pages and downloads', async (t) => {
  const options = await fixture(t);
  const initial = await assembleCourse(options);
  await buildExercises(initial.outputDir);
  await put(options.courseDir, 'sidebars.ts', `export default {topics: [{type: 'autogenerated', dirName: '01-topic'}]};`);
  const result = await assembleCourse(options);
  await buildExercises(result.outputDir);
  assert.deepEqual(result.documents, ['01-topic/01-first.md', '01-topic/02-second.mdx', 'other/hidden.md']);
  await assert.rejects(fs.access(path.join(result.outputDir, 'docs/index.md')));
  await assert.rejects(fs.access(path.join(result.outputDir, 'docs/exercises')));
  await assert.rejects(fs.access(path.join(result.outputDir, 'static/exercises')));
  // Root autogeneration includes new topics but never turns solution READMEs into pages.
  await put(options.courseDir, 'sidebars.ts', `export default {all: [{type: 'autogenerated', dirName: '.'}]};`);
  const all = await assembleCourse(options);
  assert.equal(all.documents.length, 7);
  assert.deepEqual(all.exercises, ['exercises/topic/one', 'exercises/topic/two']);
  assert.ok(!all.documents.some((file) => file.includes('/solution/')));
});

test('invalid selection fails without replacing the last successful assembly', async (t) => {
  const options = await fixture(t);
  const initial = await assembleCourse(options);
  const before = await fs.readFile(path.join(initial.outputDir, '.assembled-course.json'), 'utf8');
  for (const sidebar of [
    `{all: ['misspelled-topic']}`,
    `{all: [{type: 'autogenerated', dirName: '../source/docs'}]}`,
    `{all: [{type: 'autogenerated', dirName: 'empty'}]}`,
  ]) {
    await put(options.courseDir, 'sidebars.ts', `export default ${sidebar};`);
    await assert.rejects(assembleCourse(options), /Unknown or excluded|must stay inside|no eligible documents/);
    assert.equal(await fs.readFile(path.join(initial.outputDir, '.assembled-course.json'), 'utf8'), before);
    assert.ok(!(await fs.readdir(options.courseDir)).some((name) => name.startsWith('.course-tmp-')));
  }
});

test('honors configured include/exclude and disabled number prefixes', async (t) => {
  const options = await fixture(t);
  await put(options.courseDir, 'docusaurus.config.cjs', `module.exports = {
    presets: [['classic', {docs: {include: ['01-topic/**'], exclude: ['**/*second*'], numberPrefixParser: false}}]],
  };`);
  await fs.rm(path.join(options.courseDir, 'docusaurus.config.ts'));
  const result = await assembleCourse(options);
  assert.deepEqual(result.documents, ['01-topic/01-first.md']);
  await put(options.courseDir, 'docusaurus.config.cjs', `module.exports = {
    presets: [['classic', {docs: {sidebarPath: './sidebars.ts', numberPrefixParser: false}}]],
  };`);
  await put(options.courseDir, 'sidebars.ts', `export default {all: ['01-topic/introduction', '01-topic/02-second']};`);
  assert.equal((await assembleCourse(options)).documents.length, 2);
});

test('refuses to overwrite an unrelated output directory', async (t) => {
  const options = await fixture(t);
  await put(options.courseDir, '.course/keep.txt', 'keep me');
  await assert.rejects(assembleCourse(options), /Refusing to replace/);
  assert.equal(await fs.readFile(path.join(options.courseDir, '.course/keep.txt'), 'utf8'), 'keep me');
});
